version: "3.7"
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ".:/app"
    command: pytest

  cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    command: ash

